# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build FMCL

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
   strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

   runs-on: ${{ matrix.os }}

   steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
         nuitka-version: main
         script-name: src/__main__.py
         enable-plugins: tk-inter
         standalone: true
         onefile: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
           name: ${{ runner.os }} Build
           path: | # match what's created for the 3 OSes
              build/*.exe
              build/*.bin
              build/*.app/**/*
