# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build FMCL

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # cache: 'pip' # caching pip dependencies
      - run: pip install pyinstaller
      - run: pyinstaller -F __main__.py
      - run: pyinstaller -F __main__.py
      - uses: actions/upload-artifact@v4
        with:
          name: FMCL-windows
          path: dist/__main__.exe
      

  # pyinstaller-build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create Executable
  #       uses: sayyid5416/pyinstaller@v1
  #       with:
  #         python_ver: '3.10'
  #         spec: 'src/__main__.py'
  #         upload_exe_with_name: 'FMCL-linux'
  #         options: -F, --name "My App", --windowed, 
  # pyinstaller-build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Create Executable
  #       uses: sayyid5416/pyinstaller@v1
  #       with:
  #         python_ver: '3.10'
  #         spec: 'src/__main__.py'
  #         upload_exe_with_name: 'FMCL-macos'
  #         options: -F, --name "My App", --windowed, 
